server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    schema: classpath:/schema-postgresql.sql
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    com:
      zaxxer:
        hikari: DEBUG
